name: accounting_app
description: اپ حسابداری و انبارداری فارسی کامل
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  jdatetime: ^2.1.0
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  image_picker: ^1.0.7
  shared_preferences: ^2.2.3
  excel: ^4.0.3
  barcode_widget: ^2.0.4
  mobile_scanner: ^5.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # اگر فونت فارسی داری بعداً اضافه کن
